name: Build
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false
        description: The token to upload coverage reports to Codecov
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: pnpm run build
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Type Check
        run: pnpm check:type
      - uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
        with:
          name: dist
          path: dist
      - uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
        with:
          name: web-csv-toolbox-wasm
          path: |
            web-csv-toolbox-wasm/**/*
            !web-csv-toolbox-wasm/src
            !web-csv-toolbox-wasm/target
            !web-csv-toolbox-wasm/Cargo.toml
            !web-csv-toolbox-wasm/Cargo.lock
            !web-csv-toolbox-wasm/.gitignore
