name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Push version tag
        id: tag
        if: ${{ steps.changesets.outputs.published == 'true' }}
        run: |
          VERSION=v$(cat package.json | jq -c ".version" -r)
          git tag $(VERSION)
          git push origin $(VERSION)
          ::set-output name=version::${VERSION}
      - name: Create Release
        if: ${{ steps.changesets.outputs.published == 'true' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: refs/tags/${{ steps.tag.outputs.version }}
          release_name: Release ${{ steps.tag.outputs.version }}
          draft: false
    outputs:
      published: ${{ steps.changesets.outputs.published }}
  prerelease:
    name: Prerelease
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: release
    if: needs.release.outputs.published == 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Creating .npmrc
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: "Release @next"
        run: |
          npx changeset version --snapshot next
          npx changeset publish --no-git-tag --snapshot --tag next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
